<a href="https://colab.research.google.com/github/malakbayramovaa/NumPy-tutorials/blob/main/Numpy_106.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# numpy -> kitabxanadir. numerical phyton sozunun qisaldilisidir. pandas arxa planda numpy uzreinde qurulub.


In [2]:
a1 = np.array([1, 2, 3])
a1.ndim, a1.shape, a1.dtype, type(a1), a1.size

(1, (3,), dtype('int64'), numpy.ndarray, 3)

In [3]:
a2 = np.array([[1,2,3], [4,5,6]])
a2.ndim, a2.shape, a2.dtype, type(a2), a2.size

(2, (2, 3), dtype('int64'), numpy.ndarray, 6)

In [4]:
a3 = np.array([[[1,2,3],
                [4,5,6]],
               [[7,8,9],
                [10,11,12]]])
a3.ndim, a3.shape, a3.dtype, type(a3), a3.size

(3, (2, 2, 3), dtype('int64'), numpy.ndarray, 12)

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
random_array = np.random.randint(0, 10, size = (3,3,5))
random_array

array([[[1, 8, 6, 7, 7],
        [5, 0, 3, 3, 2],
        [4, 5, 3, 5, 4]],

       [[1, 1, 6, 7, 6],
        [3, 4, 6, 3, 2],
        [4, 8, 2, 8, 7]],

       [[5, 6, 6, 5, 0],
        [6, 4, 8, 3, 9],
        [0, 3, 6, 9, 5]]])

In [7]:
np.random.seed(42)
random_array = np.random.randint(0, 10, size = (2,3,3))
random_array

array([[[6, 3, 7],
        [4, 6, 9],
        [2, 6, 7]],

       [[4, 3, 7],
        [7, 2, 5],
        [4, 1, 7]]])

In [8]:
random_array[0,2]

array([2, 6, 7])

In [9]:
random_array[:, :, 2]

array([[7, 9, 7],
       [7, 5, 7]])

In [10]:
np.random.seed(42)
random_array = np.random.randint(0, 10, size = (3,3,2))
random_array

array([[[6, 3],
        [7, 4],
        [6, 9]],

       [[2, 6],
        [7, 4],
        [3, 7]],

       [[7, 2],
        [5, 4],
        [1, 7]]])

In [11]:
random_array[:, 2, :]

array([[6, 9],
       [3, 7],
       [1, 7]])

In [12]:
np.random.seed(42)
random_array = np.random.randint(0, 10, size = (5))
random_array

array([6, 3, 7, 4, 6])

In [13]:
random_array[::-1]

array([6, 4, 7, 3, 6])

In [14]:
np.random.randn(3,3) # -> normal distribution. adeten -3 le 3 arasinda reqemler qaytarir

array([[-0.91682684, -0.12414718, -2.01096289],
       [-0.49280342,  0.39257975, -0.92918467],
       [ 0.07983181, -0.1595165 ,  0.02222183]])

In [15]:
np.random.rand(3, 3)  # -> uniform distribution, ozunden reqemler yaradir her birinin gelme ehtimali bir birine beraberdir. adeten 0 la 1 araliginda reqemler qaytarir

array([[0.39986097, 0.04666566, 0.97375552],
       [0.23277134, 0.09060643, 0.61838601],
       [0.38246199, 0.98323089, 0.46676289]])

In [16]:
np.zeros(shape = (3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(shape = (3,3) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a1


array([1, 2, 3])

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a1 + 2

array([3, 4, 5])

In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a2 + a1

array([[2, 4, 6],
       [5, 7, 9]])

In [23]:
a1 ** 2

array([1, 4, 9])

In [24]:
a1.shape, a2.shape

((3,), (2, 3))

In [25]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [26]:
a4 = np.array([[1,2],
       [2,3]])
a4

array([[1, 2],
       [2, 3]])

In [27]:
a5 = np.array([[3,2],
       [7, 5]])
a5

array([[3, 2],
       [7, 5]])

In [28]:
a4 * a5

array([[ 3,  4],
       [14, 15]])

In [29]:
np.random.seed(42)
random_array = np.random.randint(0,10, size = (2,5,3))
random_array[1,1,:]

array([5, 1, 4])

In [30]:
# np.matmul(a1,a2), a1 @ a2, np.dot(a1, a2) -> eyni funksiyani yerine yetirir


In [31]:
ones = np.ones(shape = (3,3))

In [32]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
low_var = np.array([1,1,1,1,1,1,2,2])
high_var = np.array([100,200,300,400,500,600,700,800])

np.std(low_var), np.std(high_var), np.var(low_var), np.var(high_var) # std -> standard variation

(np.float64(0.4330127018922193),
 np.float64(229.128784747792),
 np.float64(0.1875),
 np.float64(52500.0))

In [34]:
np.argmax(high_var)    # en boyuk reqemin indeksini qaytarir.

np.int64(7)

In [35]:
np.max(high_var)    # en boyuk reqemi qaytarir

np.int64(800)

In [36]:
np.argmin(high_var )    # en kicik reqemin indeksini qaytarir

np.int64(0)

In [37]:
high_var + 10    # her birinin uzerine 10 elave edir.

array([110, 210, 310, 410, 510, 610, 710, 810])